version: 2
jobs:
  archlinux:
    docker:
      - image: base/archlinux:latest
    steps:
      - checkout
      - run:
          name: Build.
          command: sudo apt-get install pkg-config pip && ./install
      - run:
          name: Show help.
          command: curate-pkg -h
      - run:
          name: Install a package.
          command: curate-pkg -i htop

  debian:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run:
          name: Build.
          command: sudo pacman -Syyu pkg-config pip && ./install
      - run:
          name: Show help.
          command: curate-pkg -h
      - run:
          name: Install a package.
          command: curate-pkg -i htop

workflows:
  version: 2
  multiple-distributions:
    jobs:
      - archlinux
      - debian
