version: r45.29a8834
jobs:
  build:
    docker:
      - image: debian:latest
    steps:
     - checkout
      - run:
          name: Show help.
          command: curate-pkg -h
      - run:
          name: Install a package.
          command: curate-pkg -i htop
  build:
    docker:
      - image: archlinux:latest
    steps:
      - checkout
      - run:
          name: Show help.
          command: curate-pkg -h
      - run:
          name: Install a package.
          command: curate-pkg -i htop
